import { useRoute, Link } from "wouter";
import { useDocument } from "@/hooks/use-documents";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Card, CardContent } from "@/components/ui/card";
import { Footer } from "@/components/Footer";
import { UrgencyBadge } from "@/components/UrgencyBadge";
import { ArrowLeft, Calendar, User, Clock, ShieldAlert, CheckCircle2, FileText, Download, Loader2 } from "lucide-react";
import { format } from "date-fns";

export default function DocumentDetail() {
  const [, params] = useRoute("/document/:id");
  const id = parseInt(params?.id || "0");
  const { data: doc, isLoading } = useDocument(id);

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="flex flex-col items-center">
          <Loader2 className="w-8 h-8 text-primary animate-spin mb-4" />
          <p className="text-muted-foreground font-medium">Analyzing document structure...</p>
        </div>
      </div>
    );
  }

  if (!doc) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-background p-4 text-center">
        <h1 className="text-2xl font-bold mb-2">Document Not Found</h1>
        <p className="text-muted-foreground mb-6">The document you're looking for doesn't exist or has been deleted.</p>
        <Link href="/">
          <Button>Return to Dashboard</Button>
        </Link>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background flex flex-col">
      {/* Header */}
      <header className="sticky top-0 z-40 bg-background/80 backdrop-blur-lg border-b">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Link href="/">
              <Button variant="ghost" size="icon" className="rounded-full">
                <ArrowLeft className="w-5 h-5" />
              </Button>
            </Link>
            <h1 className="font-display font-semibold text-lg truncate max-w-[200px] sm:max-w-md">
              {doc.title}
            </h1>
            <UrgencyBadge level={doc.extractedData.urgency} className="hidden sm:inline-flex" />
          </div>
          
          <Button variant="outline" size="sm" onClick={() => window.print()}>
            <Download className="w-4 h-4 mr-2" /> Export
          </Button>
        </div>
      </header>

      <main className="flex-grow py-8 px-4 sm:px-6 lg:px-8">
        <div className="max-w-5xl mx-auto space-y-8">
          
          {/* AI Warning Banner */}
          <div className="bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-xl p-4 flex items-start gap-3">
            <ShieldAlert className="w-5 h-5 text-amber-600 dark:text-amber-500 flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-sm font-medium text-amber-900 dark:text-amber-200">
                AI Generated Analysis
              </p>
              <p className="text-sm text-amber-800/80 dark:text-amber-300/80 mt-1">
                This summary is generated by AI to help you understand the document. It is not legal advice. 
                Always consult with a qualified lawyer for serious legal matters.
              </p>
            </div>
          </div>

          <div className="grid lg:grid-cols-3 gap-8">
            {/* Left Col: Analysis */}
            <div className="lg:col-span-2 space-y-6">
              
              <Tabs defaultValue="summary" className="w-full">
                <TabsList className="grid w-full grid-cols-3 mb-6 p-1 bg-muted/50 rounded-xl h-12">
                  <TabsTrigger value="summary" className="rounded-lg data-[state=active]:bg-white data-[state=active]:shadow-sm">Summary</TabsTrigger>
                  <TabsTrigger value="keypoints" className="rounded-lg data-[state=active]:bg-white data-[state=active]:shadow-sm">Key Points</TabsTrigger>
                  <TabsTrigger value="action" className="rounded-lg data-[state=active]:bg-white data-[state=active]:shadow-sm">Action Plan</TabsTrigger>
                </TabsList>

                <TabsContent value="summary" className="space-y-4 animate-in fade-in slide-in-from-bottom-2 duration-500">
                  <Card className="border-none shadow-lg shadow-black/5">
                    <CardContent className="p-6 sm:p-8">
                      <h2 className="font-display font-bold text-2xl mb-4">Simplified Summary</h2>
                      <div className="prose prose-blue dark:prose-invert max-w-none">
                        <p className="text-lg leading-relaxed text-foreground/90">
                          {doc.extractedData.summary}
                        </p>
                      </div>
                    </CardContent>
                  </Card>
                </TabsContent>

                <TabsContent value="keypoints" className="animate-in fade-in slide-in-from-bottom-2 duration-500">
                  <Card className="border-none shadow-lg shadow-black/5">
                    <CardContent className="p-6 sm:p-8">
                      <h2 className="font-display font-bold text-2xl mb-6">Critical Information</h2>
                      <ul className="space-y-4">
                        {doc.extractedData.keyPoints.map((point, i) => (
                          <li key={i} className="flex gap-4 p-4 rounded-xl bg-muted/30 border border-muted-foreground/10">
                            <div className="w-6 h-6 rounded-full bg-primary/10 text-primary flex items-center justify-center flex-shrink-0 font-bold text-sm">
                              {i + 1}
                            </div>
                            <span className="text-foreground/90 leading-relaxed">{point}</span>
                          </li>
                        ))}
                      </ul>
                    </CardContent>
                  </Card>
                </TabsContent>

                <TabsContent value="action" className="animate-in fade-in slide-in-from-bottom-2 duration-500">
                  <Card className="border-none shadow-lg shadow-black/5 bg-gradient-to-br from-white to-blue-50/50 dark:from-card dark:to-blue-900/10">
                    <CardContent className="p-6 sm:p-8">
                      <h2 className="font-display font-bold text-2xl mb-6 flex items-center gap-2">
                        <CheckCircle2 className="w-6 h-6 text-green-600" />
                        Recommended Actions
                      </h2>
                      <div className="prose prose-blue dark:prose-invert max-w-none">
                        <div className="whitespace-pre-wrap text-lg leading-relaxed font-medium text-foreground/80">
                          {doc.extractedData.actionPlan}
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                </TabsContent>
              </Tabs>

              {/* Original Text Expansion */}
              <div className="border rounded-2xl overflow-hidden bg-card">
                <details className="group">
                  <summary className="flex items-center justify-between p-4 cursor-pointer hover:bg-muted/50 transition-colors">
                    <span className="font-medium flex items-center gap-2">
                      <FileText className="w-4 h-4 text-muted-foreground" />
                      View Original Extracted Text
                    </span>
                    <span className="text-muted-foreground group-open:rotate-180 transition-transform">▼</span>
                  </summary>
                  <div className="p-4 bg-muted/20 border-t max-h-96 overflow-y-auto font-mono text-sm text-muted-foreground leading-relaxed whitespace-pre-wrap">
                    {doc.originalText || "No text extracted available."}
                  </div>
                </details>
              </div>

            </div>

            {/* Right Col: Metadata */}
            <div className="space-y-6">
              <Card className="border-none shadow-md overflow-hidden">
                <div className="h-2 bg-primary w-full" />
                <CardContent className="p-6 space-y-6">
                  <h3 className="font-display font-bold text-lg">Document Details</h3>
                  
                  <div className="space-y-4">
                    <div className="flex gap-3 items-start">
                      <div className="w-8 h-8 rounded-lg bg-blue-50 dark:bg-blue-900/30 flex items-center justify-center text-blue-600 flex-shrink-0">
                        <User className="w-4 h-4" />
                      </div>
                      <div>
                        <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Sender</p>
                        <p className="font-medium">{doc.extractedData.extractedFields.sender || "Unknown Sender"}</p>
                      </div>
                    </div>

                    <div className="flex gap-3 items-start">
                      <div className="w-8 h-8 rounded-lg bg-purple-50 dark:bg-purple-900/30 flex items-center justify-center text-purple-600 flex-shrink-0">
                        <Calendar className="w-4 h-4" />
                      </div>
                      <div>
                        <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Document Date</p>
                        <p className="font-medium">{doc.extractedData.extractedFields.date || "Not specified"}</p>
                      </div>
                    </div>

                    <div className="flex gap-3 items-start">
                      <div className="w-8 h-8 rounded-lg bg-red-50 dark:bg-red-900/30 flex items-center justify-center text-red-600 flex-shrink-0">
                        <Clock className="w-4 h-4" />
                      </div>
                      <div>
                        <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Deadline</p>
                        <p className="font-medium text-red-600 dark:text-red-400">
                          {doc.extractedData.extractedFields.deadline || "No immediate deadline detected"}
                        </p>
                      </div>
                    </div>
                  </div>

                  {doc.extractedData.extractedFields.demands && doc.extractedData.extractedFields.demands.length > 0 && (
                    <div className="pt-6 border-t">
                      <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-3">Detected Demands</p>
                      <div className="flex flex-wrap gap-2">
                        {doc.extractedData.extractedFields.demands.map((demand, i) => (
                          <span key={i} className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-muted text-foreground">
                            {demand}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}

                  <div className="pt-6 border-t flex justify-between items-center text-sm text-muted-foreground">
                    <span>Type detected:</span>
                    <span className="font-medium text-foreground">{doc.extractedData.detectedDocType || "General Document"}</span>
                  </div>
                </CardContent>
              </Card>

              <div className="p-4 rounded-xl bg-secondary/10 border border-secondary/20">
                <h4 className="font-semibold text-sm mb-2">Need a lawyer?</h4>
                <p className="text-sm text-muted-foreground mb-3">
                  This document has <span className="font-medium text-foreground">{doc.extractedData.urgency} Urgency</span>. 
                  Based on the content, we recommend consulting a property lawyer.
                </p>
                <Button variant="outline" size="sm" className="w-full bg-background">
                  Find Lawyers Nearby
                </Button>
              </div>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
